# lando rebuild -y
# lando composer install
# lando php artisan key:generate
# lando php artisan migrate
# lando php -i | grep upload_max_filesize
# lando ssh --service appserver --user root --command "cat /etc/passwd"
# lando conteiner location
# /path/to/my/app => /app
# $HOME => /user
# https://laravel.lndo.site
name: seuprojeto
recipe: lamp
config:
  # php: '7.4'
  # php: '8.3'
  php: '8.2'
  composer_version: 2-latest
  webroot: public
  xdebug: true
services:
  appserver:
    run_as_root:
      - ln -snf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
      - echo "America/Sao_Paulo" > /etc/timezone 
    type: php:custom
    overrides:
      # image: lando/php:7.4-custom
      # image: lando/php:8.3
      image: lando/php:8.2
      build:
        context: ./
        dockerfile: Dockerfile.custom
      ports:
        - "80"
    config:
      # Override php settings
      php: php.ini
  database:
    # type: mysql:5.7
    type: mysql:8.0
    creds:
      user: seuprojeto
      password: seuprojeto
      database: seuprojeto
# Por conta do uso de senha única o endereço dos projetos fica fixo em laravel.lndo.site, dessa forma para desenvolvimento tem-se um único oauth consumidor cadastrado.
proxy:
  appserver:
    - laravel.lndo.site